apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wordstatistics
  description: A software component for analyzing and generating statistics on word usage within text data.
  annotations:
    github.com/project-slug: Musquan/WordStatistics
    jira/project-key: SCRUM
    jira/label: backstage-component:wordstatistics
spec:
  type: application
  owner: ICS
  lifecycle: experimental